export const authTexts = {
  login: 'Log in',
  signUp: 'Sign up',
  welcomeBack: 'Welcome back',
  getStarted: 'Get started',
  loginTitle: 'Log in to see your matches',
  loginCopy: 'Enter your credentials and let Kindred surface people who share your interests.',
  signUpTitle: 'Create your account',
  signUpCopy: 'Join Kindred and connect with people who share your interests.',
  firstName: 'First name',
  firstNamePlaceholder: 'Asha',
  lastName: 'Last name',
  lastNamePlaceholder: 'Patel',
  email: 'Email',
  emailPlaceholder: 'you@example.com',
  password: 'Password',
  passwordPlaceholder: '••••••••',
  confirmPassword: 'Confirm password',
  forgotPassword: 'Forgot password?',
  working: 'Working...',
  signedIn: 'You are signed in.',
  logout: 'Log out',
} as const
